image: python:3.6

variables:
  DEBIAN_FRONTEND: noninteractive

before_script:
  - pip3 install -r requirements/test_black.txt

all_tests:
  script:
    - pytest --disable-pytest-warnings
    - coverage report
    - black -l 100 --check .
    - flake8 .
    - python setup.py check
  when: on_success
